#!/usr/bin/env bash
set -euo pipefail

export XPT_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${XPT_HOME}/test/core.sh"

tests="$(find "$XPT_HOME/test" -iname "${1:-}*_test.sh")"

for test in $tests; do
   source "$test"
done

test::finish
