#!/usr/bin/env bash
set -euo pipefail

export XPT_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${XPT_HOME}/src/main.sh"

sha256() {
   if platform::command_exists sha256sum; then
      sha256sum
   elif platform::command_exists shasum; then
      shasum -a 256
   elif platform::command_exists openssl; then
      openssl dgst -sha256
   else
      echoerr "Unable to calculate sha256!"
      exit 43
   fi
}

header() {
   echo "$*"
   echo
}

cd "$XPT_HOME"

header "git pull"
git pull

version="$(grep VERSION "${XPT_HOME}/xpt" | grep -Eo '[0-9\.]+')"
tag="v${version}"
tar="https://github.com/denisidoro/xpt/archive/${tag}.tar.gz"
formula="/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xpt.rb"

header "Attempting to release version ${tag}..."
read -p "Press enter to continue"

header "git tag"
git tag -a "$tag" -m "$tag"

header "git push"
git push --follow-tags

header "rm formula"
rm "$formula" 2>/dev/null || true

header "tar sha256"
sha="$(curl -sL "$tar" | sha256 | awk '{print $1}')"

header "output"
echo "  url \"${tar}\""
echo "  sha256 \"${sha}\""